animales_catalogo:
    resource: "@AnimalesCatalogoBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    defaults:  { _locale: %locale% }
    requirements:
        _locale: en|es

init_route:
    pattern:   /
    defaults:  { _controller: AnimalesCatalogoBundle:Default:index, _locale: %locale% }

user_zone:
    resource: "@UserZoneBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /usuario
    
login:
    pattern:   /login
    defaults:  { _controller: AnimalesCatalogoBundle:Login:index }
login_check:
    pattern:   /login_check

admin_login:
    pattern:   /login-admin
    defaults:  { _controller: AdminSettingsBundle:Default:index }
admin_check:
    pattern:   /admin_check


user_cuenta:
   resource: "@UserZoneBundle/Controller/UserController.php"
   type:     annotation
   prefix:   /cuenta
   defaults: {_locale: es}

user_cuenta_en:
   resource: "@UserZoneBundle/Controller/UserController.php"
   type:     annotation
   prefix:   /acount
   defaults: {_locale: en}



admin_settings:
    resource: "@AdminSettingsBundle/Controller/"
    type:     annotation
    prefix:   /admin








