animales_catalogo:
    resource: "@AnimalesCatalogoBundle/Controller/"
    type:     annotation
    prefix:   /
admin_settings:
    resource: "@AdminSettingsBundle/Controller/"
    type:     annotation
    prefix:   /

