animales_catalogo:
    resource: "@AnimalesCatalogoBundle/Controller/"
    type:     annotation
    prefix:   /

user_zone:
    resource: "@UserZoneBundle/Controller/"
    type:     annotation
    prefix:   /

admin_settings:
    resource: "@AdminSettingsBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: AnimalesCatalogoBundle:Login:index }
login_check:
    pattern:   /login_check

