security:
    firewalls:
        # backend
        #admin:
        #    pattern:    ^/admin
        #    http_basic: ~
        #    provider: administradores
        admin:
            pattern:    ^/admin
            http_basic: ~
            provider: admins
        # frontend
        user:
            pattern: ^/*
            anonymous: ~
            provider: usuarios
            form_login:
                login_path: home
                check_path: login_check
            logout:
                path: logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/usuario, roles: ROLE_USUARIO }

    providers:
        # in_memory
        # admin
        #administradores:
        #    memory:
        #        users:
        #            admin: { password: adrian, roles: 'ROLE_ADMIN' }
        admins:
            entity: { class: User\ZoneBundle\Entity\User, property: email }

        # frontend                
        usuarios:
            entity: { class: User\ZoneBundle\Entity\User, property: email }


    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        User\ZoneBundle\Entity\User: { algorithm: sha512, iterations: 10 }
        User\ZoneBundle\Entity\User: { algorithm: sha512, iterations: 10 }