<?php

namespace Animales\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Cache\ApcCache;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

// 1:findAllCategories()
	/**
	 * Encuentra todas las categorias y subcategorias
	 */
	public function findAllCategories(){

		$em = $this->getEntityManager();
        $query = $em->createQuery(
                                    'SELECT 
                                      c,s
                                  	 FROM 
                                      AnimalesCatalogoBundle:Category c
                                     LEFT JOIN c.subcategories s 
                                     ORDER BY c.name ASC, s.name ASC'
                                    
        );

         $result= $query->useResultCache(true)->getArrayResult();
         $cacheDriver = new ApcCache();
		 $cacheDriver->save('AllCategories', $result); 
        
		return $result;
	} 


}
