<?php

namespace Animales\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\Common\Cache\ApcCache;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

//1  getAllProducts
	/**
	 * Todos los productos
	 */
	public function getAllProducts(){
		$em = $this->getEntityManager();
		$dql =  'SELECT p,i,s
                 FROM AnimalesCatalogoBundle:Product p
                 JOIN p.subcategory s
                 JOIN p.image i
                ';
        $query = $em->createQuery($dql);

        $result= $query->useResultCache(true)->getArrayResult();
        $cacheDriver = new ApcCache();
		$cacheDriver->save('ListProducts', $result); 
         
		return $result;


	}


	// Un producto [id / nombre]
	public function getProduct($id, $slug){}
	
	// Ultimos productos 10
	public function getLastProducts(){}

}
