<?php

namespace Animales\CatalogoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Cache\ApcCache;
/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends EntityRepository
{

//1: findSubCategoryProducts
	/**
	 * Encuentra todos los productos de una subcategoria
	 */
	public function findSubCategoryProducts($slug){
		$em = $this->getEntityManager();
		$dql =  'SELECT s,p,
						c.name, c.slug
                 FROM AnimalesCatalogoBundle:SubCategory s
                 JOIN s.products p
                 JOIN s.category c
                 WHERE s.slug = :slug';

        $query = $em->createQuery($dql)
        			->setParameter('slug',$slug);

        $result= $query->useResultCache(true)->getArrayResult();
        $cacheDriver = new ApcCache();
		$cacheDriver->save('AllProducts'.$slug, $result); 
         
		return $result;
	}

// 2: findAllCategory
	/**
	 * Encontrar todas las subcategorias de una categoria con productos
	 */
	public function findAllCategory($slug){
		// slug categoria
		$em = $this->getEntityManager($slug);
		$dql= 'SELECT  s,p,
						c.name, c.slug,
						COUNT(p.id) as number_products
                 FROM AnimalesCatalogoBundle:SubCategory s
                 LEFT JOIN s.products p
                 LEFT JOIN s.category c
                 WHERE c.slug = :slug GROUP BY s.id ORDER BY s.name ASC';

        $query = $em->createQuery($dql)
        			->setParameter('slug', $slug);

         $result= $query->useResultCache(true)->getArrayResult(); 

         if($result)
         {
        	$cacheDriver = new ApcCache();
			$cacheDriver->save('SubcategoriesProducts'.$slug, $result);
         	return $result;
         }else{

         	return $this->findAllCS($slug);
         }

	}

// 3: findAllCS
	/**
	 * Encontrar todas las subcategorias de una categoria
	 */
	public  function findAllCS($slug){
		// slug categoria
		$em = $this->getEntityManager($slug);
		$dql= 'SELECT 
               c,s
               FROM 
               AnimalesCatalogoBundle:Category c
               LEFT JOIN c.subcategories s ';
        $dql.= "WHERE c.slug = :slug ORDER BY s.name ASC";


        $query = $em->createQuery($dql)
        			->setParameter('slug', $slug);

        $result= $query->useResultCache(true)->getArrayResult(); 
        $result= $query->useResultCache(true)->getArrayResult();
        $cacheDriver = new ApcCache();
		$cacheDriver->save('Subcategories'.$slug, $result);
        
		return $result;
	} 
}
